server:
  port: 8081

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/authdb?authSource=admin

jwt:
  secret: my-secret-key
  expiration: 3600000 # 1 hour

cloud:
  config:
    label: main
