server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: patient-service
          uri: lb://patient-service
          predicates:
            - Path=/patients/**
        - id: doctor-service
          uri: lb://doctor-service
          predicates:
            - Path=/doctors/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
