spring:
  application:
    name: config-defaults
  data:
    mongodb:
      uri: mongodb://mongo:27017/
  kafka:
    bootstrap-servers: kafka:9092
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    config:
      label: main

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
